"""add field is_teacher and id_student to user model

Revision ID: 35091677c2a9
Revises: 8b28d0d0b650
Create Date: 2025-03-31 16:07:23.180036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35091677c2a9'
down_revision: Union[str, None] = '8b28d0d0b650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_teacher', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('is_student', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_student')
    op.drop_column('user', 'is_teacher')
    # ### end Alembic commands ###
